### ISSUE TITLE
how would I restrict the import of a particular library

### ISSUE THREAD

**Issue by FishmanL** [zopefoundation/RestrictedPython#197]
I just need to prevent the import of inspect (specifically, for avoiding getattr_static()), how would I set up a policy to do this?

**Comment by d-maurer** [comment]
FishmanL wrote at 2020-7-5 13:38 -0700:
>I just need to prevent the import of inspect (specifically, for avoiding getattr_static()), how would I set up a policy to do this?

I fear that in order to safely prevent the import of a specific
module you must prevent other things as well.

An example:
Controlling imports is achieved via a custom `__import__`.
However, if someone can import `implib`, he can define its own
import function and then import anything.

Thus, in order to prevent the import of say `inspect`, you
must also prevent the import of `implib`.
In addition, you must prevent the import of any module
which has already imported `inspect` or control attribute
access to modules. Otherwise, `inspect` could be obtained
indirectly via this module.

You can look at `AccessControl.ZopeGuards` for
an example how to control imports.
